### ISSUE TITLE
adding EEMs

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/STM_Sys_Board#25]
Since most Sinara devices out there right now do not have DIOT, a stand alone STM32/ECP5-based controller that also supports EEM would be a lot nicer for the transition period. 
Humpback is very limited in [EEM count](https://github.com/sinara-hw/Humpback/issues/16) and [FPGA size](https://github.com/sinara-hw/Humpback/issues/15) and needs the bulky Nucleo board. 

I know this is a big ask layout-wise, but would it be possible to somehow squeeze in the EEMs or potentially just do an EEM variant?

**Comment by jordens** [comment]
IMHO his is a step into the wrong direction. Evaluate whether you'd be much better off (especially in the long and mid term) with any of the alternative solutions in the shared design space: a dedicated combined cpu+peripheral board, one of the existing cpu/soc "carrier" boards plus a peripheral mezzanine, or a diot controller module plus peripheral module.
Please do consider supporting the move to diot!

**Comment by marmeladapk** [comment]
It's not possible to add EEM connectors on this board. But we have a [DIOT EEM Adapter](https://github.com/sinara-hw/DIOT_EEM_Adapter) which enables us to support EEMs until all of them are moved to DIOT form factor.
